---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                Assets/.*|
                Packages/.*|
                ProjectSettings/.*
            )$
      - id: no-commit-to-branch
      - id: trailing-whitespace
        exclude: |
            (?x)^(
                Assets/.*|
                Packages/.*|
                ProjectSettings/.*
            )$
